### PR TITLE
Task 2

### PR DESCRIPTION
**Pull request by maksumov**
Manually configured S3/Cloudfront resources:

- S3 URL: http://maksumov-manual-bucket.s3-website-eu-west-1.amazonaws.com/
- CF URL: https://d2jep3onnfjhls.cloudfront.net/
- Some screenshots of manual deployment process: https://drive.google.com/drive/folders/1ck0DgVya0HJRlq3bKyMGYOqdnQ9CvYS8?usp=sharing

Automatically configured S3/Cloudfront resources:

- S3 URL: http://maksumov-second-rs-app.s3-website-eu-west-1.amazonaws.com
- CF URL: https://d5lnnoyr61ghv.cloudfront.net

### CODE REVIEW

**Comment by maksumov** [comment]
Feel free to comment my work here.

**Comment by candentira** [comment]
S3 URL: http://maksumov-manual-bucket.s3-website-eu-west-1.amazonaws.com/ & S3 URL: http://maksumov-second-rs-app.s3-website-eu-west-1.amazonaws.com aren't accessible, I get 403 response. Most likely this is due to those S3 buckets being used by CloudFront.
@maksumov could you please ensure S3 links are working correctly? Creating new S3 buckets shouldn't take too much time (Manual&Automated).

**Comment by candentira** [comment]
@maksumov please let me know if you don't want to create extra buckets due to billing of used S3 resource.

**Comment by maksumov** [comment]
> S3 URL: http://maksumov-manual-bucket.s3-website-eu-west-1.amazonaws.com/ & S3 URL: http://maksumov-second-rs-app.s3-website-eu-west-1.amazonaws.com aren't accessible, I get 403 response. Most likely this is due to those S3 buckets being used by CloudFront.
> @maksumov could you please ensure S3 links are working correctly? Creating new S3 buckets shouldn't take too much time (Manual&Automated).

S3 buckets works in full compliance with the evaluation criteria specified in the [EVALUATION CRITERIA](https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task2-serve-spa-aws/task.md#evaluation-criteria):

> EVALUATION CRITERIA:
> PLEASE USE YOUR OWN - PUBLIC, GITHUB - REPOSITORY FOR TASK IMPLEMENTATION AND PRs CREATION
>
> 0 - Nothing has been done. (Link to repository is not provided. Nothing to check.)
> 3 - S3 bucket has been created and configured properly. The app has been uploaded to the bucket and is available though the Internet. Nothing else has been done. (Link to S3 bucket/website is provided. There is no Pull Request in the YOUR OWN frontend repository.)
> 4 - In addition to the previous work a CloudFront distribution is created and configured properly and the site is served now with CloudFront and is available through the Internet over CloudFront URL, not S3-website link (due to changes in bucket’s policy...). ( **Link to CloudFront website is provided. S3-website shows 403 Access Denied error.** There is no Pull Request in the YOUR OWN frontend repository.)
> 5 - Serverless-finch and serverless-single-page-app plugins are added and configured. The app can be built and deployed by running npm script command. (Link to CloudFront website is provided. PR with all changes is submitted in the YOUR OWN frontend repository and its link is provided for review.)

They **shouldn't** be accessible. They should show 403 Access Denied error.

**Comment by candentira** [comment]
@maksumov it's not specified that CloudFront has to use same bucket that was created in 2.1.2.
My perception of requirements was that we have to provide 4 working links + 2 S3 with 403 per each CloudFront.

No big issue, I can see manual steps done in screenshots attached.

**Comment by maksumov** [comment]
S3 bucket content should be accessible only in case if I didn't create Cloudfront distribution. But I did.

When I created Cloudfront manually, one of the steps was to modify the S3 policy according to the lecture. So I made the contents of the S3 bucket unavailable directly. I think the contents of the S3 bucket should be available only through Cloudfront. Cloudfront cannot work with two S3 buckets at the same time. If you need to show that I can provide access to the site via S3 directly, there is no problem with creating another S3 bucket.

**Comment by candentira** [comment]
Both S3 bucket link and CloudFront link would be accessible if CloudFront would be using **separate** s3 bucket, not the same as the one created previously in scope of 2.1.2. In that case before manually creating CloudFront you would have to create NEW bucket for it (or specify NEW bucket name for automatic creation).

There **could be** 4 S3 buckets created in scope of current task: manually created, automatically created, manually created for CloudFront, automatically created while creating CloudFront. Those buckets that are used by CloudFront must be unavailable publicly.

> If you need to show that I can provide access to the site via S3 directly, there is no problem with creating another S3 bucket.

That was what I was trying to ask you to do in the first place. But again, as you have other proofs of work done (screenshots) - it's not strictly required, all good.

We have different opinions about requirements and result format. I didn't have any intent to evaluate based on formalities, was trying to check manual steps. There are no concerns from my side.

**Comment by maksumov** [comment]
Here's a link to the newly created S3: [http://maksumov-manual-aws-task2.s3-website-eu-west-1.amazonaws.com/](http://maksumov-manual-aws-task2.s3-website-eu-west-1.amazonaws.com/)

**Pull request merged**
